
red: 
  - "FF0000"
blue:
  - "0021FF"
orange: 
  - "E7DE00"
green: 
  - "00E738"
yellow: 
  - "D7E700"
purple: 
  - "7F00E7"
cyan: 
  - "00FFEA"
magenta:
  - "E70080"
white: 
  - "FFFFFF"
black: 
  - "000000"

foreground: 
  - "FFFFFF"
background: 
  - "4E0053"
cursor: 
  - "FFFFFF"

