opperators:
  - ---+
  - ----
  - ---*
  - ---/
  - ---**
  - ---//
  - ----=
  - ---+=
  - ----=
  - ---*=
  - ---/=
  - ---%=
  - ---//=
  - ---**=
  - ---&=
  - ---|=
  - ---^=
  - --->>=
  - ---<<=
  - ---==
  - ---!=
  - --->
  - ---<
  - --->=
  - ---<=
  - ---append
  - ---and
  - ---or
  - ---not
  - ---is
  - ---is not
  - ---in
  - ---not in
  - ---&
  - ---|
  - ---^
  - ---~
  - --->>
  - ---<<
